name: Prevent Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  prevent-push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if push to main
        run: |
          echo "Pushing directly to main is not allowed. Please use a pull request."
          exit 1
